# Prometheus configuration for ETL observability and system monitoring
global:
  scrape_interval: 15s      # Scrape targets every 15 seconds
  evaluation_interval: 15s  # Evaluate rules every 15 seconds
  
  external_labels:
    monitor: 'etl-observability'
    environment: 'development'

# Scrape configurations
scrape_configs:
  # Job 1: Monitor Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Job 2: Monitor system metrics from host machine
  - job_name: 'system-metrics'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    scrape_timeout: 10s

  # Job 3: Monitor ETL application metrics
  - job_name: 'etl-metrics'
    static_configs:
      - targets: ['airflow-webserver:8000']
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: '/metrics'