apiVersion: 1

datasources:
  # PostgreSQL
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: ${POSTGRES_DB}
    user: ${POSTGRES_USER}
    jsonData:
      sslmode: 'disable'
      postgresVersion: 1500
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    isDefault: true
    editable: true

  # Prometheus
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: true